#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged || exit 1

# Fail on direct commits to main
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
  echo "No committing directly to main"
  exit 1
fi

