name: Generate Repository File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install & Prepare
        run: yarn

      - name: Generate all.json
        run: node scripts/generateRepositoryFile.js

      - name: Commit and push (if changed)
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git commit -am "Updated repository/all.json" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
